version: "3"
services:
    postgres:
        image: "postgres:latest"
    redis:
        image: "redis:latest"
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3050:80"
        depends_on:
            - api
            - client

    # This used to be called "server", but we modified to avoid keyword conflict within nginx/default.conf
    api:
        build:
            dockerfile: Dockerfile.dev
            # Look in the "server" directory
            context: ./server
        volumes:
            # Leave this folder as-is
            - /app/node_modules
            # When container tries to access anything in /app (except node_modules above) =  then redirect to ./server outside container
            - ./server:/app
        environment:
            # We can reference the named service defined above
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
